/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.inmobiliaria.view;

import com.inmobiliaria.controller.AgenteController;
import com.inmobiliaria.model.AgenteComercial;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class PanelAgentes extends javax.swing.JPanel {
    
    private Dashboard dashboard;

    /**
     * Creates new form Agentes
     * @param dashboard
     */
    public PanelAgentes(Dashboard dashboard) {
        initComponents();
        this.dashboard = dashboard;
        mostrarAgentes();
    }
    
    private void mostrarAgentes() {
        
    DefaultTableModel modelo = (DefaultTableModel) tablaAgentes.getModel();
    modelo.setRowCount(0);

    AgenteController controller = new AgenteController();

    try {
        for (AgenteComercial agente : controller.listarTodos()) {
            modelo.addRow(new Object[]{
                agente.getCedula(),
                agente.getFechaExpDoc(),
                agente.getNombres(),
                agente.getApellidos(),
                agente.getFechaNacimiento(),
                agente.getDireccion(),
                agente.getCorreo(),
                agente.getCelular(),
                agente.getCorreo(),
                agente.getContrasena(),
                agente.getRol()
            });
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error al cargar agentes: " + ex.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAgentes = new javax.swing.JTable();
        btnNuevoRegistro = new javax.swing.JButton();
        btnActualizarAgente = new javax.swing.JButton();
        btnEliminarAgente = new javax.swing.JButton();
        btnConsultarAgente = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtConsulta = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(985, 582));

        content.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agentes Registrados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 13), new java.awt.Color(51, 51, 51))); // NOI18N

        tablaAgentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cedula", "Fecha expedición", "Nombres", "Apellidos", "Fecha de nacimiento", "Dirección", "Correo", "Celular", "Login", "Contraseña", "Rol"
            }
        ));
        jScrollPane1.setViewportView(tablaAgentes);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 963, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
        );

        btnNuevoRegistro.setBackground(new java.awt.Color(212, 167, 140));
        btnNuevoRegistro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNuevoRegistro.setForeground(new java.awt.Color(51, 51, 51));
        btnNuevoRegistro.setText("Nuevo");
        btnNuevoRegistro.setToolTipText("");
        btnNuevoRegistro.setBorderPainted(false);
        btnNuevoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoRegistroActionPerformed(evt);
            }
        });

        btnActualizarAgente.setBackground(new java.awt.Color(212, 167, 140));
        btnActualizarAgente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizarAgente.setForeground(new java.awt.Color(51, 51, 51));
        btnActualizarAgente.setText("Modificar");
        btnActualizarAgente.setBorderPainted(false);
        btnActualizarAgente.setFocusPainted(false);
        btnActualizarAgente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarAgenteActionPerformed(evt);
            }
        });

        btnEliminarAgente.setBackground(new java.awt.Color(212, 167, 140));
        btnEliminarAgente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarAgente.setForeground(new java.awt.Color(51, 51, 51));
        btnEliminarAgente.setText("Eliminar");
        btnEliminarAgente.setBorderPainted(false);
        btnEliminarAgente.setFocusPainted(false);

        btnConsultarAgente.setBackground(new java.awt.Color(212, 167, 140));
        btnConsultarAgente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConsultarAgente.setForeground(new java.awt.Color(51, 51, 51));
        btnConsultarAgente.setText("Consultar");
        btnConsultarAgente.setBorderPainted(false);
        btnConsultarAgente.setFocusPainted(false);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Ingrese el número de cédula del agente");

        txtConsulta.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel12)
                .addGap(27, 27, 27)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultarAgente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(contentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(contentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNuevoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnActualizarAgente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnEliminarAgente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnConsultarAgente, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(43, 43, 43)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizarAgente, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarAgente, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoRegistroActionPerformed
        dashboard.showJPanel(new FormAgente(this.dashboard));
    }//GEN-LAST:event_btnNuevoRegistroActionPerformed

    private void btnActualizarAgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarAgenteActionPerformed
        /*showJPanel(new FormAgente());
        FormAgente form = new FormAgente(agenteExistente);
        form.setVisible(true);*/
    }//GEN-LAST:event_btnActualizarAgenteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarAgente;
    private javax.swing.JButton btnConsultarAgente;
    private javax.swing.JButton btnEliminarAgente;
    private javax.swing.JButton btnNuevoRegistro;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAgentes;
    private javax.swing.JTextField txtConsulta;
    // End of variables declaration//GEN-END:variables
}
