/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.inmobiliaria.view.panels;

import com.inmobiliaria.controller.ContratoClienteController;
import com.inmobiliaria.model.ContratoCliente;
import com.inmobiliaria.view.Dashboard;
import com.inmobiliaria.view.forms.FormContratoCliente;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class PanelContratosClientes extends javax.swing.JPanel {
    
    private final Dashboard dashboard;

    /**
     * Creates new form Agentes
     * @param dashboard
     */
    public PanelContratosClientes(Dashboard dashboard) {
        initComponents();
        this.dashboard = dashboard;
        MostrarContratosCliente();
    }
    
    private void MostrarContratosCliente() {
        
        //tabla modelo no editable
        DefaultTableModel tablaModelo = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) { //no permite editar
                return false;
            }
        };

        tablaModelo.setColumnIdentifiers(new Object[] {
            "Codigo", "Descripcion", "Modalidad", "Fecha creacion", "Fecha expiracion", "Valor", "Fiador", "Telefono",
            "Agente", "Cliente"
        });

        ContratoClienteController ContratoClienteController = new ContratoClienteController();

        try {
            for (ContratoCliente ContratoClienteModel : ContratoClienteController.listarTodos()) {

                tablaModelo.addRow(new Object[]{
                    ContratoClienteModel.getCodigo(),
                    ContratoClienteModel.getDescripcion(),
                    ContratoClienteModel.getModalidadComercializacion(),
                    ContratoClienteModel.getFechaCreacion(),
                    ContratoClienteModel.getFechaExpiracion(),
                    ContratoClienteModel.getValor(),
                    ContratoClienteModel.getNombreFiador(),
                    ContratoClienteModel.getCelularFiador(),
                    ContratoClienteModel.getCedulaAgente(),
                    ContratoClienteModel.getCedulaCliente()
                });
            }
            tablaContratos.setModel(tablaModelo);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar agentes: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaContratos = new javax.swing.JTable();
        btnNuevoRegistro = new javax.swing.JButton();
        btnActualizarContratoCl = new javax.swing.JButton();
        btnEliminarContratoCl = new javax.swing.JButton();
        btnConsultarContratoCl = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtConsulta = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(985, 582));

        content.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agentes Registrados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 13), new java.awt.Color(51, 51, 51))); // NOI18N

        tablaContratos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaContratos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 963, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
        );

        btnNuevoRegistro.setBackground(new java.awt.Color(212, 167, 140));
        btnNuevoRegistro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNuevoRegistro.setForeground(new java.awt.Color(51, 51, 51));
        btnNuevoRegistro.setText("Nuevo");
        btnNuevoRegistro.setToolTipText("");
        btnNuevoRegistro.setBorderPainted(false);
        btnNuevoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoRegistroActionPerformed(evt);
            }
        });

        btnActualizarContratoCl.setBackground(new java.awt.Color(212, 167, 140));
        btnActualizarContratoCl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizarContratoCl.setForeground(new java.awt.Color(51, 51, 51));
        btnActualizarContratoCl.setText("Modificar");
        btnActualizarContratoCl.setBorderPainted(false);
        btnActualizarContratoCl.setFocusPainted(false);
        btnActualizarContratoCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarContratoClActionPerformed(evt);
            }
        });

        btnEliminarContratoCl.setBackground(new java.awt.Color(212, 167, 140));
        btnEliminarContratoCl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarContratoCl.setForeground(new java.awt.Color(51, 51, 51));
        btnEliminarContratoCl.setText("Eliminar");
        btnEliminarContratoCl.setBorderPainted(false);
        btnEliminarContratoCl.setFocusPainted(false);
        btnEliminarContratoCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarContratoClActionPerformed(evt);
            }
        });

        btnConsultarContratoCl.setBackground(new java.awt.Color(212, 167, 140));
        btnConsultarContratoCl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConsultarContratoCl.setForeground(new java.awt.Color(51, 51, 51));
        btnConsultarContratoCl.setText("Consultar");
        btnConsultarContratoCl.setBorderPainted(false);
        btnConsultarContratoCl.setFocusPainted(false);
        btnConsultarContratoCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarContratoClActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Ingrese el código del contrato");

        txtConsulta.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel12)
                .addGap(27, 27, 27)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultarContratoCl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(contentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(contentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNuevoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnActualizarContratoCl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnEliminarContratoCl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnConsultarContratoCl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(43, 43, 43)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizarContratoCl, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarContratoCl, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        jPanel3.getAccessibleContext().setAccessibleName("Contratos con Clientes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoRegistroActionPerformed
        dashboard.showJPanel(new FormContratoCliente(this.dashboard));
    }//GEN-LAST:event_btnNuevoRegistroActionPerformed

    private void btnActualizarContratoClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarContratoClActionPerformed
        
        int fila = tablaContratos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione el contrato.");
            return;
        }
        // consultar contrato seleccionado por codigo
        int codigoContrato = Integer.parseInt(tablaContratos.getValueAt(fila, 0).toString());
        
        ContratoClienteController ContratoClienteController = new ContratoClienteController();
        ContratoCliente contratoEditar;
        
        try {
            contratoEditar = ContratoClienteController.consultarCodigo(codigoContrato); //obtener datos
            if (contratoEditar != null) {
                FormContratoCliente form = new FormContratoCliente(dashboard, contratoEditar);
                dashboard.showJPanel(form);
            } else {
                JOptionPane.showMessageDialog(this, "Contrato no encontrado.");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar el contrato. " + ex.getMessage());
        }
        
    }//GEN-LAST:event_btnActualizarContratoClActionPerformed

    private void btnEliminarContratoClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarContratoClActionPerformed
        
        int fila = tablaContratos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione el contrato.");
            return;
        }
        
        int codigo = Integer.parseInt(tablaContratos.getValueAt(fila, 0).toString());
        
        int confirmacion = JOptionPane.showConfirmDialog(this, "Seguro desea eliminar el contrato?", "Confirmacion", JOptionPane.WARNING_MESSAGE);
        System.out.println(confirmacion);

        try {
            if (confirmacion == 0) {
                ContratoClienteController ContratoClienteController = new ContratoClienteController();
                boolean eliminado = ContratoClienteController.eliminar(codigo);

                if (eliminado) {
                    JOptionPane.showMessageDialog(this, "Contrato eliminado correctamente.");
                    MostrarContratosCliente();
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo eliminar el contrato.");
                } 
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar contrato: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarContratoClActionPerformed

    private void btnConsultarContratoClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarContratoClActionPerformed
        
        if (txtConsulta.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el código del contrato.");
        return;
        }
        
        int codigo = Integer.parseInt(txtConsulta.getText());
        
        ContratoClienteController ContratoClienteController = new ContratoClienteController();
        ContratoCliente contratoEditar;
        
        try {
            contratoEditar = ContratoClienteController.consultarCodigo(codigo); //obtener datos
            if (contratoEditar != null) {
                FormContratoCliente form = new FormContratoCliente(dashboard, contratoEditar);
                dashboard.showJPanel(form);
            } else {
                JOptionPane.showMessageDialog(this, "Contrato no encontrado.");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar el contrato. " + ex.getMessage());
        }
        
    }//GEN-LAST:event_btnConsultarContratoClActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarContratoCl;
    private javax.swing.JButton btnConsultarContratoCl;
    private javax.swing.JButton btnEliminarContratoCl;
    private javax.swing.JButton btnNuevoRegistro;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaContratos;
    private javax.swing.JTextField txtConsulta;
    // End of variables declaration//GEN-END:variables
}
